q10
SELECT E.PNOME, E.UNOME, E.ENDERECO
FROM EMPREGADO E, DEPARTAMENTO D
WHERE D.DNOME = 'Pesquisa'
AND D.DNUMERO = E.DNO;

SELECT E.PNOME, E.UNOME, E.ENDERECO, D.DNOME
FROM EMPREGADO E, DEPARTAMENTO D
WHERE D.DNUMERO = E.DNO
AND D.DNOME = 'Administração';


Q11
SELECT P.PNUMERO, P.DNUM, E.UNOME, E.DATANASC, E.ENDERECO
FROM PROJETO P, DEPARTAMENTO D, EMPREGADO E
WHERE P.DNUM = D.DNUMERO
AND D.GERCPF = E.CPF
AND P.PLOCALIZACAO = 'Stafford';


SELECT P.PNUMERO, P.PLOCALIZACAO, P.PJNOME, D.DNOME, D.DNUMERO, E.UNOME, E.DATANASC, E.ENDERECO
FROM PROJETO P, DEPARTAMENTO D, EMPREGADO E
WHERE P.DNUM = D.DNUMERO
AND D.GERCPF = E.CPF
--AND P.PLOCALIZACAO = 'Stafford';

SELECT P.*
FROM PROJETO P
WHERE P.PLOCALIZACAO = 'Stafford';

SELECT P.PNUMERO, P.PLOCALIZACAO, P.DNUM, D.DNOME
FROM PROJETO P, DEPARTAMENTO D
WHERE P.DNUM = D.DNUMERO;


SELECT E.PNOME, E.UNOME, S.PNOME, S.UNOME
FROM EMPREGADO E, EMPREGADO S
WHERE E.GERENTE_CPF = S.CPF;

SELECT E.PNOME, E.UNOME, E.CPF, S.PNOME, S.UNOME, E.GERENTE_CPF, S.CPF
FROM EMPREGADO E 
     JOIN EMPREGADO S ON E.GERENTE_CPF = S.CPF;
	 
	 
SELECT E.CPF, D.DNUMERO
FROM EMPREGADO E, DEPARTAMENTO D 
--WHERE E.DNO = D.DNUMERO;

SELECT E.SALARIO
FROM EMPREGADO E
ORDER BY E.SALARIO;

SELECT DISTINCT E.SALARIO
FROM EMPREGADO E;


SELECT E.SALARIO, COUNT(E.SALARIO) AS QTD
FROM EMPREGADO E
GROUP BY E.SALARIO;

SELECT D.DNOME, COUNT(*) AS QTD
FROM EMPREGADO E JOIN DEPARTAMENTO D ON E.DNO = D.DNUMERO
GROUP BY D.DNOME;


SELECT D.DNOME, COUNT(*) AS QTD
FROM EMPREGADO E, DEPARTAMENTO D 
WHERE E.DNO = D.DNUMERO
GROUP BY D.DNOME;

SELECT S.PNOME, COUNT(*) AS QTD, AVG(E.SALARIO) AS MEDIA_SALARIO
FROM EMPREGADO S JOIN EMPREGADO E ON S.CPF = E.GERENTE_CPF
GROUP BY S.PNOME;


SELECT E.CPF
FROM EMPREGADO E
WHERE E.DNO = 5

UNION

SELECT DISTINCT E.GERENTE_CPF
FROM EMPREGADO E
WHERE E.DNO = 5;


SELECT E.CPF
FROM EMPREGADO E
WHERE E.DNO = 5

UNION

SELECT DISTINCT E.GERENTE_CPF
FROM EMPREGADO E
WHERE E.DNO = 5;


SELECT E.CPF
FROM EMPREGADO E
WHERE E.DNO = 5

EXCEPT

SELECT DISTINCT E.GERENTE_CPF
FROM EMPREGADO E
WHERE E.DNO = 5;


SELECT E.CPF
FROM EMPREGADO E
WHERE E.DNO = 5

INTERSECT

SELECT DISTINCT E.GERENTE_CPF
FROM EMPREGADO E
WHERE E.DNO = 5;
